name: device_info_plus_webos
description: "Device info plus plugin implementation for webOS"
version: 0.1.1
repository: https://github.com/dinaraparanid/device_info_plus_webos

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DeviceInfoPlusWebOSWeb
        fileName: src/device_info_plus_webos.dart
